//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XayDungMinhThanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoCompany
    {
        public int id { get; set; }
        public string name { get; set; }
        public string intro { get; set; }
        public string address { get; set; }
        public string tenGiamDoc { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string mst { get; set; }
    }
}
